#!/usr/bin/env php
<?php

$folder = getcwd();
$prefix = sprintf('git -C ' . $folder);
$command = 'checkout';
$options = 'checkout';
$argument = 'checkout';
$options = [];

//var_dump($folder);
//var_dump($prefix);

if (isset($argv[1], $argv[2]) &&  $argv[1] === 'check') {
    $branches = [];
    foreach (run($prefix, 'branch', '', '') as $branch) {
        $branch = trim(ltrim($branch, '*'));

        if (strpos($branch, $argv[2]) !== false) {
            $branches[] = $branch;
        }

        if ($branch === $argv[2]) {
            $branches = [$branch];
            break;
        }
    }

    if (count($branches) === 1) {
        $result = run($prefix, 'checkout', '', $branches[0]);
        printResult($result);
    } else {
        var_dump('found 0 or >1 branches');
        var_dump($branches);
        die;
    }
} else {
    var_dump('undefined command');
    die;
}

function run($prefix, $command, $options, $argument) {
    $result = [];
    exec($prefix . ' ' .$command . ' ' . $options . ' ' . $argument, $result);

    return $result;
}

function printResult($result) {
    print(PHP_EOL);
    foreach ($result as $line) {
        print($line . PHP_EOL);
    }
    print(PHP_EOL);
}